/*
========================================
LUMILIST BACKGROUND SERVICE WORKER
========================================
Handles keyboard shortcut (Ctrl+Shift+Y) and quick save with notifications
*/

// Import Dexie and background sync module
// FIX [H14]: Track whether scripts loaded successfully
let _scriptsLoaded = false;
let _scriptLoadError = null;

if (typeof importScripts === 'function') {
    try {
        importScripts('lib/dexie.js');
        importScripts('background-sync.js');
        importScripts('background/review-prompts.js');
        importScripts('background/quick-save.js');
        importScripts('background/title-fetch.js');
        _scriptsLoaded = true;
    } catch (e) {
        console.error('Failed to import scripts:', e);
        _scriptLoadError = e.message || 'Unknown error loading scripts';
    }
} else {
    // Firefox packaged build can run background scripts in document scope (no importScripts).
    // In that mode, Dexie, BackgroundSync, and helper background modules are expected to be
    // loaded via manifest script order generated by the Firefox release packager.
    const hasDexie = typeof Dexie !== 'undefined';
    const hasBackgroundSync = typeof BackgroundSync !== 'undefined';
    const hasReviewPromptHelpers = typeof resolveReviewPromptUserId === 'function'
        && typeof requestReviewPromptDisplay === 'function'
        && typeof applyReviewPromptAction === 'function';
    const hasQuickSaveHelpers = typeof quickSaveCurrentTab === 'function'
        && typeof saveAllTabs === 'function';
    const hasTitleFetchHelpers = typeof fetchPageTitle === 'function'
        && typeof fetchFaviconLinksFromPage === 'function'
        && typeof fetchFaviconAsBase64 === 'function';
    _scriptsLoaded = hasDexie
        && hasBackgroundSync
        && hasReviewPromptHelpers
        && hasQuickSaveHelpers
        && hasTitleFetchHelpers;
    if (!_scriptsLoaded) {
        _scriptLoadError = 'Required background globals missing in non-worker background context';
        console.error(_scriptLoadError);
    }
}

// FIX [H12]: Track database initialization state
let _dbReady = false;
let _dbInitPromise = null;

// FIX [Critical #1]: Mutex locks to prevent concurrent Quick Save / Save All operations
// Without these, rapid clicks or Ctrl+Shift+Y + popup can create duplicate bookmarks/boards
let _isQuickSaving = false;
let _isSaveAllRunning = false;

// Hard limit for Save All Tabs to prevent sync queue overflow and abuse
const MAX_SAVE_ALL_TABS = 500;

// Bookmark limit constants (must match newtab.js)
const BOOKMARK_LIMIT = 100000;
const BACKGROUND_GET_PAGES_LOGIN_SYNC_STATE_STORAGE_KEY = 'lumilist_login_sync_state';

const SYNC_RETRY_ALARM_NAME = 'lumilistSyncRetry';
const SYNC_RETRY_ALARM_PERIOD_MINUTES = 1;
const SYNC_PUSH_PENDING_STORAGE_KEY = 'syncPushPending';

function normalizeSchedulePushDelayMs(delayMs) {
    const parsed = Number(delayMs);
    return Number.isFinite(parsed) && parsed >= 0
        ? Math.floor(parsed)
        : undefined;
}

function scheduleBackgroundPushIfNeeded(syncOptions = {}) {
    if (typeof BackgroundSync === 'undefined') return;
    if (syncOptions?.schedulePush === false) return;

    try {
        BackgroundSync.schedulePush(normalizeSchedulePushDelayMs(syncOptions?.delayMs));
    } catch (error) {
        console.warn('[Background] Failed to schedule sync push:', error);
    }
}

function normalizeGetPagesLoginSyncState(rawState) {
    if (!rawState || typeof rawState !== 'object') return null;
    const userId = (typeof rawState.userId === 'string' && rawState.userId.trim())
        ? rawState.userId.trim()
        : null;
    const phase = (typeof rawState.phase === 'string' && rawState.phase.trim())
        ? rawState.phase.trim()
        : null;

    if (!userId || !phase) return null;

    return {
        userId,
        phase
    };
}

function ensureSyncRetryAlarm() {
    try {
        chrome.alarms.create(SYNC_RETRY_ALARM_NAME, {
            periodInMinutes: SYNC_RETRY_ALARM_PERIOD_MINUTES
        });
    } catch (error) {
        console.warn('[Background] Failed to create sync retry alarm:', error);
    }
}

async function recoverPendingSyncWork(trigger = 'worker-load') {
    if (!_scriptsLoaded || typeof BackgroundSync === 'undefined') return;

    try {
        if (typeof ensureDbReady === 'function') {
            const dbReady = await ensureDbReady();
            if (!dbReady) {
                console.warn(`[Background] Skipping pending sync recovery after ${trigger}: IndexedDB unavailable`);
                return;
            }
        }

        const [storageState, queueStatus] = await Promise.all([
            chrome.storage.local.get([SYNC_PUSH_PENDING_STORAGE_KEY]),
            BackgroundSync.getQueueStatus()
        ]);
        const hasPendingFlag = !!storageState?.[SYNC_PUSH_PENDING_STORAGE_KEY];
        const pendingCount = Number(queueStatus?.pending) || 0;
        const processingCount = Number(queueStatus?.processing) || 0;
        const hasQueuedWork = pendingCount > 0 || processingCount > 0;

        if (!hasPendingFlag && !hasQueuedWork) {
            return;
        }

        console.info(`[Background] Recovering pending sync work after ${trigger}`, {
            hasPendingFlag,
            pendingCount,
            processingCount
        });

        await BackgroundSync.forcePush();
    } catch (error) {
        console.warn(`[Background] Failed to recover pending sync work after ${trigger}:`, error);
    }
}

ensureSyncRetryAlarm();
void recoverPendingSyncWork('worker-load');

chrome.runtime.onInstalled.addListener(() => {
    ensureSyncRetryAlarm();
    void recoverPendingSyncWork('onInstalled');
});

chrome.runtime.onStartup.addListener(() => {
    ensureSyncRetryAlarm();
    void recoverPendingSyncWork('onStartup');
});

chrome.alarms.onAlarm.addListener((alarm) => {
    if (alarm?.name !== SYNC_RETRY_ALARM_NAME) return;
    void recoverPendingSyncWork('syncRetryAlarm');
});

chrome.storage.onChanged.addListener((changes, areaName) => {
    if (areaName !== 'local' || !changes?.lumilist_user || typeof BackgroundSync === 'undefined') {
        return;
    }

    const oldUserId = changes.lumilist_user.oldValue?.id || null;
    const newUserId = changes.lumilist_user.newValue?.id || null;

    if (!oldUserId) {
        return;
    }

    if (!newUserId || newUserId !== oldUserId) {
        console.info('[Background] Clearing queued sync work after auth account change', {
            oldUserId,
            newUserId
        });
        void BackgroundSync.clearAllQueued();
    }
});

function sendBackgroundRuntimeUnavailable(sendResponse, action = 'unknown') {
    const errorMessage = _scriptLoadError || 'Background runtime failed to initialize';
    console.error(`[Background] Runtime unavailable for action "${action}":`, errorMessage);
    sendResponse({
        success: false,
        error: errorMessage,
        code: 'background_runtime_unavailable'
    });
}


// Listen for messages from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    // SECURITY FIX: Only accept messages from this extension
    // Prevents malicious websites from triggering extension actions
    if (sender.id !== chrome.runtime.id) {
        console.warn('[Background] Rejected message from unauthorized sender:', sender.id);
        sendResponse({ success: false, error: 'Unauthorized' });
        return;
    }

    if (!_scriptsLoaded) {
        sendBackgroundRuntimeUnavailable(sendResponse, request?.action);
        return;
    }

    if (request.action === 'reviewPromptTrackManualBookmark') {
        (async () => {
            try {
                const userId = await resolveReviewPromptUserId(request.userId);
                if (!userId) {
                    sendResponse({ success: false, error: 'User not found' });
                    return;
                }
                const count = clampPositiveInteger(request.count, 0, 1000000);
                if (count > 0) {
                    await trackReviewPromptManualBookmarks(userId, count);
                }
                sendResponse({ success: true });
            } catch (error) {
                console.error('[ReviewPrompt] track manual bookmark failed:', error);
                sendResponse({ success: false, error: error.message });
            }
        })();
        return true;
    }

    if (request.action === 'reviewPromptTrackIssue') {
        (async () => {
            try {
                const userId = await resolveReviewPromptUserId(request.userId);
                if (!userId) {
                    sendResponse({ success: false, error: 'User not found' });
                    return;
                }
                await trackReviewPromptIssue(userId, request.issueType || 'general');
                sendResponse({ success: true });
            } catch (error) {
                console.error('[ReviewPrompt] track issue failed:', error);
                sendResponse({ success: false, error: error.message });
            }
        })();
        return true;
    }

    if (request.action === 'reviewPromptRequestDisplay') {
        (async () => {
            try {
                const userId = await resolveReviewPromptUserId(request.userId);
                if (!userId) {
                    sendResponse({ success: false, showPrompt: false, reason: 'user_not_found' });
                    return;
                }
                const result = await requestReviewPromptDisplay(userId, request.trigger || 'manual');
                sendResponse({
                    success: true,
                    showPrompt: !!result.showPrompt,
                    reason: result.reason || (result.showPrompt ? 'eligible' : 'unknown')
                });
            } catch (error) {
                console.error('[ReviewPrompt] display check failed:', error);
                sendResponse({ success: false, showPrompt: false, reason: 'error', error: error.message });
            }
        })();
        return true;
    }

    if (request.action === 'reviewPromptHandleAction') {
        (async () => {
            try {
                const userId = await resolveReviewPromptUserId(request.userId);
                if (!userId) {
                    sendResponse({ success: false, error: 'User not found' });
                    return;
                }
                await applyReviewPromptAction(userId, request.userAction || 'dismiss');
                sendResponse({ success: true });
            } catch (error) {
                console.error('[ReviewPrompt] handle action failed:', error);
                sendResponse({ success: false, error: error.message });
            }
        })();
        return true;
    }


    if (request.action === 'quickSave') {
        quickSaveCurrentTab()
            .then(result => {
                
                sendResponse(result);
            })
            .catch(error => {
                console.error('Error in quickSave:', error);
                sendResponse({ success: false, message: error.message });
            });
        return true;
    }

    if (request.action === 'saveAllTabs') {
        saveAllTabs()
            .then(result => {
                
                sendResponse(result);
            })
            .catch(error => {
                console.error('Error in saveAllTabs:', error);
                sendResponse({ success: false, message: error.message });
            });
        return true;
    }

    if (request.action === 'getPages') {
        (async () => {
            try {
                // Return list of pages for the settings dropdown (exclude deleted)
                // No longer requires login for local-only use
                const pages = await db.pages.orderBy('order').filter(p => !p.deletedAt).toArray();
                sendResponse({ pages: pages.map(p => ({ id: p.id, name: p.name })) });
            } catch (error) {
                console.error('Error getting pages:', error);
                sendResponse({ pages: [] });
            }
        })();
        return true;
    }

    if (request.action === 'fetchPageTitle') {
        
        fetchPageTitle(request.url)
            .then(result => {
                
                sendResponse(result);
            })
            .catch(error => {
                console.warn('[FetchTitle] Handler error:', error?.message || error);
                sendResponse({ success: false, title: '', error: error.message });
            });
        return true; // Keep channel open for async response
    }

    // Resolve favicon URLs from page HTML link tags (<link rel="icon" ...>)
    if (request.action === 'fetchFaviconLinksFromPage') {
        fetchFaviconLinksFromPage(request.url, { timeoutMs: request.timeoutMs })
            .then(icons => sendResponse({ success: true, icons }))
            .catch(err => sendResponse({ success: false, error: err.message, icons: [] }));
        return true; // Keep channel open for async response
    }

    // Background sync handlers
    if (request.action === 'queueSync') {
        
        if (typeof BackgroundSync !== 'undefined') {
            BackgroundSync.addToSyncQueue(request.payload)
                .then((queued) => {
                    if (queued === false) {
                        sendResponse({ success: false, error: 'Sync queue is full. Please wait for pending changes to sync.' });
                        return;
                    }
                    scheduleBackgroundPushIfNeeded(request.payload?.syncOptions);
                    sendResponse({ success: true });
                })
                .catch(error => {
                    console.error('[Background] queueSync error:', error);
                    sendResponse({ success: false, error: error.message });
                });
        } else {
            console.error('[Background] BackgroundSync not loaded');
            sendResponse({ success: false, error: 'BackgroundSync not available' });
        }
        return true;
    }

    // Batch sync handler for bulk imports (single IPC call for multiple operations)
    if (request.action === 'queueBatchSync') {
        
        const batchPayload = Array.isArray(request.payload)
            ? { operations: request.payload, syncOptions: {} }
            : (request.payload || {});
        const operations = Array.isArray(batchPayload.operations) ? batchPayload.operations : [];

        if (typeof BackgroundSync !== 'undefined' && operations.length > 0) {
            BackgroundSync.addBatchToSyncQueue(operations)
                .then(result => {
                    scheduleBackgroundPushIfNeeded(batchPayload.syncOptions);
                    sendResponse({ success: true, added: result });
                })
                .catch(error => {
                    console.error('[Background] queueBatchSync error:', error);
                    sendResponse({ success: false, error: error.message });
                });
        } else {
            console.error('[Background] BackgroundSync not loaded or invalid payload');
            sendResponse({ success: false, error: 'Invalid request' });
        }
        return true;
    }

    if (request.action === 'forcePush') {
        
        if (typeof BackgroundSync !== 'undefined') {
            // FIX: Use async handler to properly await push completion before responding
            // This ensures flushSyncQueue() in newtab.js waits for actual server push
            (async () => {
                const FORCE_PUSH_TIMEOUT = 90000;
                try {
                    const timeoutPromise = new Promise((_, reject) =>
                        setTimeout(() => reject(new Error(`forcePush timeout after ${FORCE_PUSH_TIMEOUT / 1000}s`)), FORCE_PUSH_TIMEOUT)
                    );
                    const result = await Promise.race([BackgroundSync.forcePush(), timeoutPromise]);
                    if (result && result.success === false) {
                        sendResponse({
                            success: false,
                            error: result.error || result.reason || 'forcePush failed',
                            result
                        });
                        return;
                    }
                    sendResponse({ success: true, result: result || { success: true } });
                } catch (error) {
                    console.error('[Background] forcePush error:', error);
                    sendResponse({ success: false, error: error.message });
                }
            })();
        } else {
            console.error('[Background] BackgroundSync not loaded');
            sendResponse({ success: false, error: 'BackgroundSync not available' });
        }
        return true; // Keep message channel open for async response
    }

    if (request.action === 'getQueueStatus') {
        
        if (typeof BackgroundSync !== 'undefined') {
            BackgroundSync.getQueueStatus()
                .then(status => sendResponse(status))
                .catch(error => sendResponse({ error: error.message }));
        } else {
            sendResponse({ error: 'BackgroundSync not available' });
        }
        return true;
    }

    if (request.action === 'clearSyncQueue') {
        
        if (typeof BackgroundSync !== 'undefined') {
            BackgroundSync.clearAllQueued()
                .then(result => sendResponse(result))
                .catch(error => sendResponse({ success: false, error: error.message }));
        } else {
            sendResponse({ success: false, error: 'BackgroundSync not available' });
        }
        return true;
    }

    // Fetch favicon as Base64 for caching (bypasses CORS issues)
    if (request.action === 'fetchFaviconAsBase64') {
        fetchFaviconAsBase64(request.url, { timeoutMs: request.timeoutMs })
            .then(base64 => sendResponse({ success: true, data: base64 }))
            .catch(err => sendResponse({ success: false, error: err.message }));
        return true; // Keep channel open for async response
    }
});
